"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    'django-insecure-#^*&s430hv7r-zx-b48rp$@d69d9q*frkxj0j!9is(pmv7$@e8',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "0.0.0.0", "backend"],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party
    'corsheaders',
    'allauth',
    'allauth.account',
    'django_rq',
    
    # Local
    'core',
]

SITE_ID = int(os.getenv("SITE_ID", "1"))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'goldmine_v2'),
        'USER': os.getenv('POSTGRES_USER', 'goldmine_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'goldmine_dev_secret'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    },
    'legacy': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('LEGACY_DB_NAME', 'legacy_goldmine'),
        'USER': os.getenv('LEGACY_DB_USER', 'root'),
        'PASSWORD': os.getenv('LEGACY_DB_PASSWORD', 'root'),
        'HOST': os.getenv('LEGACY_DB_HOST', 'legacy_db'),
        'PORT': os.getenv('LEGACY_DB_PORT', '3306'),
    }
}

# Support common `DATABASE_URL` style configuration (e.g. Render Postgres connection strings).
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    parsed = urlparse(_database_url)
    if parsed.scheme in {"postgres", "postgresql"}:
        query = parse_qs(parsed.query)
        sslmode = (query.get("sslmode") or [None])[0]

        options: dict[str, str] = {}
        if sslmode:
            options["sslmode"] = sslmode

        DATABASES["default"] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (parsed.path or "").lstrip("/") or os.getenv("POSTGRES_DB", "goldmine_v2"),
            "USER": unquote(parsed.username or "") or os.getenv("POSTGRES_USER", "goldmine_user"),
            "PASSWORD": unquote(parsed.password or "") or os.getenv("POSTGRES_PASSWORD", "goldmine_dev_secret"),
            "HOST": parsed.hostname or os.getenv("POSTGRES_HOST", "db"),
            "PORT": str(parsed.port or 5432),
            **({"OPTIONS": options} if options else {}),
        }

# Background job queue (Redis)
RQ_QUEUES = {
    "default": {
        "HOST": os.getenv("REDIS_HOST", "redis"),
        "PORT": int(os.getenv("REDIS_PORT", "6379")),
        "DB": int(os.getenv("REDIS_DB", "0")),
        "DEFAULT_TIMEOUT": int(os.getenv("REDIS_DEFAULT_TIMEOUT", "600")),
    }
}

# Support `REDIS_URL` configuration (e.g. Render Key Value connection strings).
_redis_url = os.getenv("REDIS_URL")
if _redis_url:
    parsed = urlparse(_redis_url)
    redis_db_raw = (parsed.path or "").lstrip("/")
    try:
        redis_db = int(redis_db_raw) if redis_db_raw else 0
    except ValueError:
        redis_db = 0

    RQ_QUEUES["default"].update(
        {
            "HOST": parsed.hostname or RQ_QUEUES["default"]["HOST"],
            "PORT": int(parsed.port or RQ_QUEUES["default"]["PORT"]),
            "DB": redis_db,
            **(
                {"PASSWORD": unquote(parsed.password or "")}
                if parsed.password is not None
                else {}
            ),
        }
    )

# CORS & CSRF
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    ["http://localhost:3000", "http://127.0.0.1:3000"],
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    ["http://localhost:3000", "http://127.0.0.1:3000"],
)

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv("STATIC_ROOT", os.path.join(BASE_DIR, "staticfiles"))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))
LECTURE_MEDIA_ROOT = os.path.join(MEDIA_ROOT, 'lectures')

# Upload limits (bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(25 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(25 * 1024 * 1024)))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Disable implicit slash-redirects that break POST/JSON API clients
APPEND_SLASH = False

# Security settings (tune via env in production)
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if env_bool("DJANGO_BEHIND_PROXY", default=False) else None
)
USE_X_FORWARDED_HOST = env_bool("DJANGO_USE_X_FORWARDED_HOST", default=False)

SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")

SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
