# Generated by Django 5.0.14 on 2026-01-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name (e.g. QM1)', max_length=255, unique=True)),
                ('long_name', models.CharField(help_text='Full display name', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year (e.g. 2023)')),
                ('semester', models.CharField(choices=[('HS', 'Fall Semester'), ('FS', 'Spring Semester')], max_length=2)),
                ('professors', models.TextField(help_text='One per line')),
                ('assistants', models.TextField(help_text='One per line')),
                ('fs_path', models.CharField(blank=True, help_text='Path on filesystem for PDF assets', max_length=1024)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_groups', to='core.lecture')),
            ],
            options={
                'ordering': ['-year', 'semester'],
                'unique_together': {('lecture', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Series number (or ordering for special sheets)')),
                ('title', models.CharField(blank=True, help_text="Special title (e.g. 'Midterm')", max_length=255)),
                ('tex_file', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.CharField(blank=True, max_length=255)),
                ('solution_file', models.CharField(blank=True, max_length=255)),
                ('semester_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.semestergroup')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Exercise number within series')),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('text_content', models.TextField(blank=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.series')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
