# Generated by ChatGPT on 2026-01-11

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='deleted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='deleted_message',
            field=models.TextField(blank=True, default=""),
        ),
    ]
