# Generated by ChatGPT on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usercomment_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='children', to='core.usercomment'),
        ),
    ]
