# Generated by Django 5.0.14 on 2026-01-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='html_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='html_rendered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='render_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='render_status',
            field=models.CharField(choices=[('not_rendered', 'Not rendered'), ('ok', 'Rendered'), ('failed', 'Failed')], default='not_rendered', max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='tex_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]

