# Generated by Django 5.0.14 on 2026-01-16 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_renderjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('assistant', 'Assistant')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.semestergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__username'],
                'unique_together': {('user', 'semester_group')},
            },
        ),
    ]
